insert into To_Do (ID,USERNAME,DESCRIPTION,TARGET_DATE,COMPLETION_STATUS)
values(10001,'ANISHKAA','Get AWS Certified',CURRENT_DATE(),false);

insert into To_Do (ID, USERNAME, DESCRIPTION, TARGET_DATE, COMPLETION_STATUS)
values(10002,'ANISHKAA', 'Get Azure Certified', CURRENT_DATE(), false);

insert into To_Do (ID, USERNAME, DESCRIPTION, TARGET_DATE, COMPLETION_STATUS)
values(10003,'ANISHKAA', 'Get GCP Certified', CURRENT_DATE(), false);

insert into To_Do (ID, USERNAME, DESCRIPTION, TARGET_DATE,COMPLETION_STATUS)
values(10004,'ANISHKAA', 'Learn DevOps', CURRENT_DATE(), false);